# Generated by Django 3.1.2 on 2020-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
